// play/element-plus/src/App.vue
<template>
<!--  <p class="pf-regular-24">pf-regular-24 </p>
  <p class="pf-medium-24"> pf-medium-24 </p>
  <p class="pf-regular-20">pf-regular-20 </p>
  <p class="pf-medium-20"> pf-medium-20 </p>
  <p class="pf-regular-18">pf-regular-18 </p>
  <p class="pf-medium-18"> pf-medium-18 </p>
  <p class="pf-regular-17">pf-regular-17 </p>
  <p class="pf-medium-17"> pf-medium-17 </p>
  <p class="pf-regular-16">pf-regular-16 </p>
  <p class="pf-medium-16"> pf-medium-16 </p>
  <p class="pf-regular-15">pf-regular-15 </p>
  <p class="pf-medium-15"> pf-medium-15 </p>
  <p class="pf-regular-14">pf-regular-14 </p>
  <p class="pf-regular-12">pf-regular-12 </p>


  <p class="din">din 9999 </p>
  <p class="din-bold"> din-bold 7600</p>
  <p class="din-heavy">din-heavy 9999</p>
  <p class="din-heavy-lighter"> din-heavy-lighter 9999</p>-->
  <ButtonDemo/>
  <BreadcrumbDemo/>
  <PaginationDemo/>
  <DialogDemo/>
  <TransferDemo/>
  <MenuDemo/>
  <AvatarDemo/>
  <RadioDemo/>
  <RadioButtonDemo/>
  <CheckboxDemo/>
  <TableDemo/>
  <TagDemo/>
  <TabsDemo/>
  <DropdownDemo/>
  <InputDemo/>
  <SelectDemo/>
  <DatePickerDemo/>
  <InputNumberDemo/>
  <SelectV2Demo/>
  <CascaderDemo/>
  <DescriptionsDemo/>
  <FormDemo/>
  <TextDemo/>
  <DividerDemo/>
  <BadgeDemo/>
  <CalendarDemo/>
  <CardDemo/>
  <CollapseDemo/>
  <TimelineDemo/>
  <TreeDemo/>
  <AutoCompleteDemo/>
  <RateDemo/>
  <SwitchDemo/>
  <SliderDemo/>
  <TimepickerDemo/>
  <TreeSelectDemo/>
  <ProgressDemo/>
  <PopconfirmDemo/>
  <PageHeaderDemo/>
  <StepsDemo/>
  <AlertDemo/>
</template>
<!--
<style scoped lang="scss">
@use '@chapanda/style-preset/theme/index' as cbd;
 .din {
   @include cbd.font-din(true);
   font-weight: 700;
 }
 .din-bold{
   @include cbd.font-din-bold();
   font-weight: 700;
 }
 .din-heavy{
   @include cbd.font-din-heavy(true)
 }
 .din-heavy-lighter{
   @include cbd.font-din-heavy-lighter()
 }

</style>-->
<script setup lang="ts">
import ButtonDemo from './components/button.vue'
import BreadcrumbDemo from './components/breadcrumb.vue'
import PaginationDemo from './components/pagination.vue'
import DialogDemo from './components/dialog.vue'
import TransferDemo from './components/transfer.vue'
import MenuDemo from './components/menu.vue'
import AvatarDemo from './components/avatar.vue'
import RadioDemo from './components/radio.vue'
import RadioButtonDemo from './components/radio-button.vue'
import CheckboxDemo from './components/checkbox.vue'
import TableDemo from './components/table.vue'
import TagDemo from './components/tag.vue'
import TabsDemo from './components/tabs.vue'
import DropdownDemo from './components/dropdown.vue'
import InputDemo from './components/input.vue'
import SelectDemo from './components/select.vue'
import SelectV2Demo from './components/select-v2.vue'
import DatePickerDemo from './components/date-picker.vue'
import InputNumberDemo from './components/input-number.vue'
import CascaderDemo from './components/cascader.vue'
import DescriptionsDemo from './components/descriptions.vue'
import FormDemo from './components/form.vue'
import TextDemo from './components/text.vue'
import DividerDemo from './components/divider.vue'
import BadgeDemo from './components/badge.vue'
import CalendarDemo from './components/calendar.vue'
import CardDemo from './components/card.vue'
import CollapseDemo from './components/collapse.vue'
import TimelineDemo from "./components/timeline.vue";
import TreeDemo from "./components/tree.vue";
import AutoCompleteDemo from "./components/auto-complete.vue";
import RateDemo from "./components/rate.vue";
import SwitchDemo from "./components/switch.vue";
import SliderDemo from './components/slider.vue'
import TimepickerDemo from './components/timepicker.vue'
import TreeSelectDemo from './components/tree-select.vue'
import ProgressDemo from './components/progress.vue'
import PopconfirmDemo from './components/popconfirm.vue'
import PageHeaderDemo from './components/page-header.vue'
import StepsDemo from './components/steps.vue'
import AlertDemo from './components/alert.vue'
</script>

// play/antd/src/App.tsx
import { Flex, ConfigProvider } from 'antd';

// import { genChaPandaAntdTheme } from '@chapanda/style-preset/antd'
import { genChaPandaAntdTheme } from '@chapanda/style-preset-antd'
import RadioDemo from './components/radio.tsx'
import AvatarDemo from './components/avatar.tsx'
import ButtonDemo from './components/button.tsx'
import CardDemo from './components/card.tsx'
import CollapseDemo from './components/collapse.tsx'
import DescriptionsDemo from './components/descriptions.tsx'
import EmptyDemo from './components/empty.tsx'
import ListDemo from './components/list.tsx'
import PopoverDemo from './components/popover.tsx'
import StatisticDemo from './components/statistic.tsx'
import TableDemo from './components/table.tsx'
import TabsDemo from './components/tabs.tsx'
import TagDemo from './components/tag.tsx'
import TimelineDemo from './components/timeline.tsx'
import TreeDemo from './components/tree.tsx'
import CascaderDemo from './components/cascader.tsx'
import CheckboxDemo from './components/checkbox.tsx'
import DatePickerDemo from './components/date-picker.tsx'
import FormDemo from './components/form.tsx'
import InputDemo from './components/input.tsx'
import MentionsDemo from './components/mentions.tsx'
import SelectDemo from './components/select.tsx'
import SlidereDemo from './components/slider.tsx'
import TransfereDemo from './components/transfer.tsx'
import TreeSelectDemo from './components/tree-select.tsx'
import UploadDemo from './components/upload.tsx'
import AlertDemo from './components/alert.tsx'
import MessageDemo from './components/message.tsx'
import NotificationDemo from './components/notification.tsx'
import PopconfirmDemo from './components/popconfirm.tsx'
import ProgressDemo from './components/progress.tsx'
import ModalDemo from './components/modal.tsx'
import BreadcrumbDemo from './components/breadcrumb.tsx'
import MenuDemo from './components/menu.tsx'
import PaginationDemo from './components/pagination.tsx'
import InputNumberDemo from './components/input-number.tsx'
import SwitchDemo from './components/switch.tsx'
import CalendarDemo from './components/calendar.tsx'

function App() {
  return (
    <ConfigProvider theme={genChaPandaAntdTheme()}>
      <Flex gap="small" wrap>
        <ButtonDemo/>
      </Flex>
      <Flex gap="small" wrap>
        <AvatarDemo/>
      </Flex>

      <Flex gap="small" wrap>
        <RadioDemo/>
      </Flex>

      <Flex gap="small" wrap>
        <CardDemo/>
      </Flex>

      <Flex gap="small" wrap>
        <CollapseDemo/>
      </Flex>

      <Flex gap="small" wrap>
        <DescriptionsDemo/>
      </Flex>

      <Flex gap="small" wrap>
        <EmptyDemo/>
      </Flex>

      <Flex gap="small" wrap>
        <ListDemo/>
      </Flex>

      <Flex gap="small" wrap>
        <PopoverDemo/>
      </Flex>

      <Flex gap="small" wrap>
        <StatisticDemo/>
      </Flex>

      <Flex gap="small" wrap>
        <TableDemo/>
      </Flex>

      <Flex gap="small" wrap>
        <TabsDemo/>
      </Flex>

      <Flex gap="small" wrap>
        <TagDemo/>
      </Flex>

      <Flex gap="small" wrap>
        <TimelineDemo/>
      </Flex>

      <Flex gap="small" wrap>
        <TreeDemo/>
      </Flex>

      <Flex gap="small" wrap>
        <CascaderDemo/>
      </Flex>

      <Flex gap="small" wrap>
        <CheckboxDemo/>
      </Flex>

      <Flex gap="small" wrap>
        <DatePickerDemo/>
      </Flex>

      <Flex gap="small" wrap>
        <FormDemo/>
      </Flex>

      <Flex gap="small" wrap>
        <InputDemo/>
      </Flex>

      <Flex gap="small" wrap>
        <MentionsDemo/>
      </Flex>

      <Flex gap="small" wrap>
        <SelectDemo/>
      </Flex>

      <Flex gap="small" wrap>
        <SlidereDemo/>
      </Flex>

      <Flex gap="small" wrap>
        <TransfereDemo/>
      </Flex>

      <Flex gap="small" wrap>
        <TreeSelectDemo/>
      </Flex>

      <Flex gap="small" wrap>
        <UploadDemo/>
      </Flex>

      <Flex gap="small" wrap>
        <AlertDemo/>
      </Flex>

      <Flex gap="small" wrap>
        <MessageDemo/>
      </Flex>

      <Flex gap="small" wrap>
        <NotificationDemo/>
      </Flex>

      <Flex gap="small" wrap>
        <PopconfirmDemo/>
      </Flex>

      <Flex gap="small" wrap>
        <ProgressDemo/>
      </Flex>

      <Flex gap="small" wrap>
        <ModalDemo/>
      </Flex>

      <Flex gap="small" wrap>
        <BreadcrumbDemo/>
      </Flex>

      <Flex gap="small" wrap>
        <MenuDemo/>
      </Flex>

      <Flex gap="small" wrap>
        <PaginationDemo/>
      </Flex>

      <Flex gap="small" wrap>
        <InputNumberDemo/>
      </Flex>

      <Flex gap="small" wrap>
        <SwitchDemo/>
      </Flex>

      <Flex gap="small" wrap>
        <CalendarDemo/>
      </Flex>
      <p className="pf-regular-24">pf-regular-24 </p>
      <p className="pf-medium-24"> pf-medium-24 </p>
      <p className="pf-regular-20">pf-regular-20 </p>
      <p className="pf-medium-20"> pf-medium-20 </p>

      <p className="font-din">din 9999 </p>
      <p className="font-din-bold"> din-bold 7600</p>
      <p className="font-din-heavy">din-heavy 9999</p>
      <p className="font-din-heavy-lighter"> din-heavy-lighter 9999</p>
    </ConfigProvider>
  )
}

export default App
